headline: Download jq
body:

  - text: |

      jq is written in C and has no runtime dependencies, so it should be
      possible to build it for nearly any platform. Prebuilt binaries are
      available for Linux, OS X and Windows.

      The binaries should just run, but on OS X and Linux you may need
      to make them executable first using `chmod +x jq`.

      jq is licensed under the MIT license. For all of the gory
      details, read the file `COPYING` in the source distribution.


      ### Linux
      
       * Binaries for [64-bit](linux64/jq) or [32-bit](linux32/jq) systems.

       * For Arch users, a PKGBUILD for jq-1.1 is in the
         [AUR](https://aur.archlinux.org/packages.php?ID=63849), as
         well as a PKGBUILD for the HEAD of master
         ([jq-git](https://aur.archlinux.org/packages.php?ID=63850)).
         You can install them using
         [Yaourt](https://wiki.archlinux.org/index.php/Yaourt) or
         manually by following instructions on [Arch Linux's
         Wiki](https://wiki.archlinux.org/index.php/Arch_UseRepository).

       * jq 1.2 is [in Debian](http://packages.debian.org/jq)

      ### OS X

       * `brew install jq` using [homebrew](http://mxcl.github.com/homebrew/)

       * Or, grab prebuilt [64-bit binaries](osx64/jq) or [32-bit
         binaries](osx32/jq)

      ### Windows

       * Executables for [64-bit](win64/jq.exe) or [32-bit](win32/jq.exe)

      ### From source on Linux or OS X

       * [Source tarball for jq $JQ_VERSION](source/jq-$JQ_VERSION.tar.gz)

      You can build it using the usual `./configure && make && sudo
      make install` rigmarole.

      If you're interested in using the lastest development version, try:

          git clone https://github.com/stedolan/jq.git
          cd jq
          autoreconf -i
          ./configure
          make
          sudo make install

      To build it from a git clone, you'll need to install a few
      packages first:

       * [Flex](http://www.gnu.org/software/flex/)
       * [Bison](http://www.gnu.org/software/bison/)
       * [GCC](http://gcc.gnu.org)
       * [Make](http://www.gnu.org/software/make)
       * [Autotools](http://www.gnu.org/software/automake)

      For Linux systems, these will all be in your system's package
      manager, and if you do development on the machine they're most
      likely already installed.

      On OS X, these are all included in Apple's command line tools, which
      can be installed from [Xcode](http://developer.apple.com/technologies/tools/).
      However, you may find that you need a newer version of Bison than the one provided
      by Apple. This can be found in [Homebrew](http://mxcl.github.com/homebrew/)
      or [MacPorts](http://macports.org/).

      `flex` and `bison` are used to generate the lexer and parser for
      jq, and some python scripts generate the UTF8 encoding tables
      needed for JSON parsing.
   
      #### Building the documentation

      jq's documentation is compiled into static HTML using
      [Bonsai](http://www.tinytree.info). To view the documentation
      locally, run `rake serve` from the docs/ subdirectory. You'll
      need a few Ruby dependencies, which can be installed by
      following the instructions in `docs/README.md`.


