#!/bin/sh

. "${0%/*}/setup" "$@"

# We set PAGER because there's a mantest for `env` that uses it.
(cd $JQBASEDIR/docs && pipenv run python3 build_mantests.py) |
    env PAGER=less $VALGRIND $Q $JQ -L "$mods" --run-tests
