headline: Download jq
body:

  - text: |

      jq is written in C and has no runtime dependencies, so it should be
      possible to build it for nearly any platform. Prebuilt binaries are
      available for Linux, OS X and Windows.

      The binaries should just run, but on OS X and Linux you may need
      to make them executable first using `chmod +x jq`.

      jq is licensed under the MIT license. For all of the gory
      details, read the file `COPYING` in the source distribution.


      ### Linux

       * jq 1.5 is in the official [Debian](https://packages.debian.org/jq) and
         [Ubuntu](http://packages.ubuntu.com/jq) repositories. Install using
         `sudo apt-get install jq`.

       * jq 1.5 is in the official
         [Fedora](http://pkgs.fedoraproject.org/cgit/jq.git/) repository.
         Install using `sudo dnf install jq`.

       * jq 1.4 is in the official [openSUSE](https://software.opensuse.org/package/jq)
         repository. Install using `sudo zypper install jq`.

       * jq 1.5 is in the official
         [Arch](https://www.archlinux.org/packages/?sort=&q=jq&maintainer=&flagged=)
         repository.  Install using `sudo pacman -Sy jq`.

       * jq 1.6 binaries for
         [64-bit](https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64)
         or
         [32-bit](https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux32).

       * jq 1.5 binaries for
         [64-bit](https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64)
         or
         [32-bit](https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux32).

       * jq 1.4 binaries for
         [64-bit](https://github.com/stedolan/jq/releases/download/jq-1.4/jq-linux-x86_64)
         or
         [32-bit](https://github.com/stedolan/jq/releases/download/jq-1.4/jq-linux-x86).

       * jq 1.3 binaries for
         [64-bit](https://github.com/stedolan/jq/releases/download/jq-1.3/jq-linux-x86_64)
         or
         [32-bit](https://github.com/stedolan/jq/releases/download/jq-1.3/jq-linux-x86).

      ### OS X

       * Use [Homebrew](http://brew.sh/) to install jq 1.5 with
         `brew install jq`.

       * jq 1.6 binary for
         [64-bit](https://github.com/stedolan/jq/releases/download/jq-1.6/jq-osx-amd64).

       * jq 1.5 binary for
         [64-bit](https://github.com/stedolan/jq/releases/download/jq-1.5/jq-osx-amd64).

       * jq 1.4 binaries for
         [64-bit](https://github.com/stedolan/jq/releases/download/jq-1.4/jq-osx-x86_64)
         or
         [32-bit](https://github.com/stedolan/jq/releases/download/jq-1.4/jq-osx-x86).

       * jq 1.3 binaries for
         [64-bit](https://github.com/stedolan/jq/releases/download/jq-1.3/jq-osx-x86_64)
         or
         [32-bit](https://github.com/stedolan/jq/releases/download/jq-1.3/jq-osx-x86).

      ### FreeBSD

       * `pkg install jq` as root installs a pre-built
         [binary package](https://www.freebsd.org/doc/en_US.ISO8859-1/books/handbook/pkgng-intro.html).

       * `make -C /usr/ports/textproc/jq install clean` as root installs the
         [jq](https://www.freshports.org/textproc/jq/)
         [port](https://www.freebsd.org/doc/en_US.ISO8859-1/books/handbook/ports-using.html)
         from source.

      ### Solaris

       * `pkgutil -i jq` in [OpenCSW](https://www.opencsw.org/p/jq) for Solaris
         10+, Sparc and x86.

       * jq 1.4 binaries for Solaris 11
         [64-bit](https://github.com/stedolan/jq/releases/download/jq-1.4/jq-solaris11-64)
         or
         [32-bit](https://github.com/stedolan/jq/releases/download/jq-1.4/jq-solaris11-32).

      ### Windows

       * Use [Chocolatey NuGet](https://chocolatey.org/) to install jq 1.5 with
         `chocolatey install jq`.

       * jq 1.6 executables for
         [64-bit](https://github.com/stedolan/jq/releases/download/jq-1.6/jq-win64.exe)
         or
         [32-bit](https://github.com/stedolan/jq/releases/download/jq-1.6/jq-win32.exe).

       * jq 1.5 executables for
         [64-bit](https://github.com/stedolan/jq/releases/download/jq-1.5/jq-win64.exe)
         or
         [32-bit](https://github.com/stedolan/jq/releases/download/jq-1.5/jq-win32.exe).

       * jq 1.4 executables for
         [64-bit](https://github.com/stedolan/jq/releases/download/jq-1.4/jq-win64.exe)
         or
         [32-bit](https://github.com/stedolan/jq/releases/download/jq-1.4/jq-win32.exe).

       * jq 1.3 executables for
         [64-bit](https://github.com/stedolan/jq/releases/download/jq-1.3/jq-win64.exe)
         or
         [32-bit](https://github.com/stedolan/jq/releases/download/jq-1.3/jq-win32.exe).

      ### Checksums and signatures

      SHA-256 checksums are provided for all release and pre-release binaries.
      They can be found under
      [sig/v1.x/sha256sum.txt](https://github.com/stedolan/jq/tree/master/sig).
      The checksums for jq 1.6 are in
      [sig/v1.6/sha256sum.txt](https://raw.githubusercontent.com/stedolan/jq/master/sig/v1.6/sha256sum.txt).
      The checksums for jq 1.5 are in
      [sig/v1.5/sha256sum.txt](https://raw.githubusercontent.com/stedolan/jq/master/sig/v1.5/sha256sum.txt).

      Additionally, all binaries are signed by the
      [jq Package Signing Key](https://raw.githubusercontent.com/stedolan/jq/master/sig/jq-release.key).
      The signatures can be found under
      [sig/v1.x/\*.asc](https://github.com/stedolan/jq/tree/master/sig).
      The signatures for jq 1.6 are in
      [sig/v1.5/\*.asc](https://github.com/stedolan/jq/tree/master/sig/v1.6).
      The signatures for jq 1.5 are in
      [sig/v1.5/\*.asc](https://github.com/stedolan/jq/tree/master/sig/v1.5).
      You can use [GnuPG](https://gnupg.org/) to verify a signature by downloading
      the signature and running `gpg --verify signature.asc`.

      ### From source on Linux, OS X, Cygwin, and other POSIX-like operating systems

       * [Source tarball for jq 1.6](https://github.com/stedolan/jq/releases/download/jq-1.6/jq-1.6.tar.gz)
       * [Source tarball for jq 1.5](https://github.com/stedolan/jq/releases/download/jq-1.5/jq-1.5.tar.gz)

      You can build it using the usual `./configure && make && sudo
      make install` rigmarole.

      If you're interested in using the lastest development version, try:

          git clone https://github.com/stedolan/jq.git
          cd jq
          autoreconf -i
          ./configure --disable-maintainer-mode
          make
          sudo make install

      To build it from a git clone, you'll need to install a few
      packages first:

       * [GCC](https://gcc.gnu.org)
       * [Make](https://www.gnu.org/software/make/)
       * [Autotools](https://www.gnu.org/software/automake/)

      For Linux systems, these will all be in your system's package
      manager, and if you do development on the machine they're most
      likely already installed.

      On OS X, these are all included in Apple's command line tools, which can
      be installed from [Xcode](https://developer.apple.com/xcode/). However,
      you may find that you need a newer version of Bison than the one provided
      by Apple. This can be found in [Homebrew](http://brew.sh) or
      [MacPorts](https://macports.org/).

      The `--disable-maintainer-mode` flag says to use the pre-generated lexer
      and parser that come with the code. To compile the lexer and parser also
      from source, leave out this flag. You will need to install
      [Flex](http://flex.sourceforge.net/) and
      [Bison](https://www.gnu.org/software/bison/).

      #### Building the documentation

      jq's documentation is compiled into static HTML using Python.
      To build the docs, run `pipenv run python3 build_website.py` from
      the docs/ subdirectory. To serve them locally, you can run
      `python3 -m SimpleHTTPServer`. You'll need a few Python dependencies,
      which can be installed by following the instructions in `docs/README.md`.

      The man page is built by `make jq.1`, or just `make`, also from
      the YAML docs, and you'll still need the Python dependencies to
      build the manpage.

