#!/bin/sh
set -eu

if [ "${1:-}" = "set-dist" ]; then
    $MESONREWRITE --sourcedir="$MESON_PROJECT_DIST_ROOT" kwargs set project / version "$2"
    exit
fi

cd "$(dirname "$0")/../"
test -e .git || exit 1

if git describe --tags --match 'jq-*' >/dev/null 2>&1; then
  git describe --tags --match 'jq-*' --dirty | sed 's/^jq-//'
else
  branch=$(git rev-parse --abbrev-ref HEAD)
  commit=$(git describe --always --dirty)
  echo "${branch}-${commit}"
fi
