current_dir = File.dirname(__FILE__)
rakefile_manual = File.expand_path(File.join(current_dir, "Rakefile.manual"))
rakefile_website = File.expand_path(File.join(current_dir, "Rakefile.website"))
rakefile_docset = File.expand_path(File.join(current_dir, "Rakefile.docset"))

desc "Build the manpage from the bonsai source of the manual"
task :manpage do
    system %(#{$0} -f #{rakefile_manual} manpage)
end

desc "Collect jq unit test cases from the bonsai source of the manual"
task :mantests do
    system %(#{$0} -f #{rakefile_manual} mantests)
end

desc "Build the website from the bonsai sources"
task :build do
    system %(#{$0} -f #{rakefile_website} build)
end

desc "Build a Dash docset from bonsai sources"
task :docset do
    system %(#{$0} -f #{rakefile_docset} build)
end

desc "Serve a live view of the website on http://localhost:5000/jq/"
task :serve do
    system %(#{$0} -f #{rakefile_website} serve)
end

