rakefile_manual = File.expand_path("Rakefile.manual", __FILE__)
rakefile_website = File.expand_path("Rakefile.website", __FILE__)

desc "Build the manpage from the bonsai source of the manual"
task :manpage do
    system %(#{$0} -f #{rakefile_manual} manpage)
end

desc "Collect jq unit test cases from the bonsai source of the manual"
task :mantests do
    system %(#{$0} -f #{rakefile_manual} mantests)
end

desc "Build the website from the bonsai sources"
task :build do
    system %(#{$0} -f #{rakefile_website} build)
end

desc "Serve a live view of the website on http://localhost:5000/jq/"
task :serve do
    system %(#{$0} -f #{rakefile_website} serve)
end

