# The key value pairs found below are available within the templates.

:url: https://stedolan.github.io/jq

# This line is modified by the Makefile. To change the version number,
# edit the Autoconf version number at the top of configure.ac
jq_version: "1.4-2-g15c4a7f-dirty"

root: '/jq'
