name: Windows Build

on:
    push:
      branches:
         - 'master'
         - 'windows-build'
      paths:
         - '**.[chly]'
         - '**/Makefile.am'
         - '.github/workflows/windows.yml'

    pull_request:
      paths:
         - '**.[chly]'
         - '**/Makefile.am'
         - '.github/workflows/windows.yml'

jobs:
    windows:
        runs-on: windows-latest
        env:
            APPVER: '10.0'
            CODESIGN_PKT: 0000000000000000
            INSTALL_DIR: C:\jq
            WINSDKVER: '10.0.22000.0'
            WIXDIR: 'c:\Program Files (x86)\Windows Installer XML v3.5'
        steps:
            - name: Clone repository
              uses: actions/checkout@v1
            - name: Find MSVC and run vcvarsall.bat
              uses: ilammy/msvc-dev-cmd@v1
              with:
                arch: amd64
            - uses: msys2/setup-msys2@v2
              with:
                update: true
                install: >-
                  base-devel
                  git
            #- name: Set up MinGW
            #  uses: egor-tensin/setup-mingw@v2
            #  with:
            #    platform: x64
            - name: Build and Test
              shell: cmd
              run: |
                title jq Build %CPU% %dbg__type%
                git submodule update --init --recursive
                mkdir %INSTALL_DIR%
                pacman --noconfirm -S autoconf
                pacman --noconfirm -S automake
                pacman --noconfirm -S bison
                set "PATH=%PATH%;C:\msys64\usr\bin;C:\cygwin\bin"
                set "PATH=%PATH%;C:\tools\cygwin\bin"
                echo PATH=%PATH%
                # Make
                autoreconf -fi
                ./configure --with-oniguruma=builtin --disable-shared --enable-static --enable-all-static
                make
                make SUBDIRS= "TESTS=tests/mantest tests/jqtest tests/onigtest tests/base64test" check
                7z a jq-windows.zip jq.exe
            - name: Upload Artifacts
              uses: actions/upload-artifact@v2
              with:
                name: Zip file
                path: jq-windows.zip
                name: Executable
                path: jq.exe
            - name: Upload Test Logs
              if: true
              uses: actions/upload-artifact@v2
              with:
                name: Test logs
                path: test-suite.log
