name: Windows Build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            git
            clang
            autoconf
            automake
            libtool
            p7zip
      - shell: msys2 {0}
        run: |
          autoreconf -fiv
          ./configure --disable-valgrind --with-oniguruma=builtin --disable-shared --enable-static --enable-all-static
          make -j4
          make SUBDIRS= "TESTS=tests/mantest tests/jqtest tests/onigtest tests/base64test" check
      - name: Upload Test Logs
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-logs
          path: |
            test-suite.log
            tests/*.log
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: jq-windows
          path: |
            jq.exe
